NUMBER_OF_PLATES    =   3;
BUILD_PLATE_WIDTH   =   120;
EXTRA_MARGIN        =   5;
HEIGHT              =   BUILD_PLATE_WIDTH/3;
TOP_FLANGE_WIDTH    =   BUILD_PLATE_WIDTH/6;
BOTTOM_FLANGE_WIDTH =   BUILD_PLATE_WIDTH/4;
THICKNESS           =   2;

